### ISSUE TITLE
希望增加自执行函数前加个分号的处理

### ISSUE THREAD

**Issue by EchoChan314** [Jianru-Lin/lambda-view#1]
`;(function(){
//这应该是一个某系统的插件js
//具体功能代码。。。
})();`
类似这类代码。

**Comment by Jianru-Lin** [comment]
目前：如果原本的代码就是这样写的，则输出时会保留。否则不会额外添加。

需要这个功能时因为碰到了什么特殊的场景吗？

**Comment by EchoChan314** [comment]
@Jianru-Lin  可以不用处理，就是去掉了美观一点而已。
