### ISSUE TITLE
代码展开以后如何重新折叠呢

### ISSUE THREAD

**Issue by nmvjhd** [Jianru-Lin/lambda-view#10]
请问大神，我有时候展开了下代码，发现是些我并不关注的信息，想重新把这部分折叠起来，请问现在支持吗？

**Comment by Jianru-Lin** [comment]
@nmvjhd 可以点击任意花括号折叠/展开代码块。另外圆括号也是能点击的，主要用于折叠/展开表达式。

**Comment by nmvjhd** [comment]
哦，明白了，建议在文档里面也说明下，这个不是那么直观。

**Comment by Jianru-Lin** [comment]
@nmvjhd 😄好的，是我偷懒了
