### ISSUE TITLE
在文件存在的情况下，输入lv app.js，提示报错 env: node\r: No such file or directory

### ISSUE THREAD

**Issue by netbeen** [Jianru-Lin/lambda-view#12]
在文件存在的情况下，输入lv app.js，提示报错 

```
env: node\r: No such file or directory
```

**Comment by netbeen** [comment]
clone源码执行后运行正常。npm install -g 的包有问题

**Comment by Jianru-Lin** [comment]
@netbeen 好的我检查下

**Comment by Jianru-Lin** [comment]
@netbeen 我无法重现。不过错误看起来是因为我在 Windows 下编辑过然后回车换行是 \r\n 而不是 \n 导致的。

我在 mac 下做了修改并重新发布了。版本号为 v4.9.0。你能帮忙试一下看看能否安装吗？非常感谢。🙏
