### ISSUE TITLE
能否加入注释的查看呢

### ISSUE THREAD

**Issue by krissss** [Jianru-Lin/lambda-view#13]
比如看bootsatrap的源码，分好多块的方式，那我还是得打开原文件来看每一块是哪个组件，因为看注释比看源码快的多

**Comment by Jianru-Lin** [comment]
@krissss 我正在做这方面的功能。之后会加入 😄

**Comment by Jianru-Lin** [comment]
@krissss 已经完成此功能。请更新到 v5.5.4 以上版本。
