### ISSUE TITLE
[Feature request] Support view online js file

### ISSUE THREAD

**Issue by Nullizer** [Jianru-Lin/lambda-view#14]
Example: `$lv https://raw.githubusercontent.com/Jianru-Lin/lambda-view/master/helper.js`

I think it should work like open in local file system, but it not:

> [2016/10/23 上午1:45:27] INFO read file from "/home/nullizer/https:/raw.githubusercontent.com/Jianru-Lin/lambda-view/master/helper.js"...
> [2016/10/23 上午1:45:27] ERROR ENOENT: no such file or directory, open '/home/nullizer/https:/raw.githubusercontent.com/Jianru-Lin/lambda-view/master/helper.js'

If possible, we can go further, support github page like `$lv https://github.com/Jianru-Lin/lambda-view/blob/master/helper.js` not raw js content sounds like more convenient

**Comment by Jianru-Lin** [comment]
I accept it, and I think it's an good idea. Maybe we can support more after that, like:

```
lv npm://package-name@ver/path/file.js
```

Then we can access specific package file in an convinient way.

**Comment by Jianru-Lin** [comment]
@Nullizer It works now. Update your lambda-view to v4.15.0 now.

```
lv https://raw.githubusercontent.com/Jianru-Lin/lambda-view/master/helper.js
```

You can see what will happen.

😄
