### ISSUE TITLE
Unexpected token %

### ISSUE THREAD

**Issue by yangzj1992** [Jianru-Lin/lambda-view#16]
在阅读[ v8 源码](https://github.com/v8/v8/blob/master/src/js/array.js)时，使用 lv 会报这样的错误

```
[2016-12-10 15:58:17] INFO read file from "v8_array.js"...
[2016-12-10 15:58:17] INFO parsing javascript source code and generating html content...
[2016-12-10 15:58:17] ERROR Line 9: Unexpected token %
```

其中，
像 9 行的 `%CheckIsBootstrapping();`  
40 行的 `var constructor = %ArraySpeciesConstructor(array);` 等等都会抛出此错误。

这些应该都是引入外部 c++ 定义的运行时函数或者构造函数..所以抛出 `Unexpected token %` 错误，想问下当阅读 js 代码遇到这样的情况要如何处理？

**Comment by Jianru-Lin** [comment]
@yangzj1992 这些以百分号开头的函数是 V8 特殊标记的一类纯 C++ 实现的函数。在 [runtime.h](https://github.com/v8/v8/blob/3dea2c83541af5c0f65044c4224f15d919254a4c/src/runtime/runtime.h) 文件中有说明。lambda-view 不会支持这种语法，因为它不属于标准的 ECMA-262 的一部分。这确实很让人烦恼。

**Comment by yangzj1992** [comment]
@Jianru-Lin  感谢回复，那么想问下有类似 lv 这样的好工具来阅读这样的混合代码吗 (. ❛ ᴗ ❛.)，感谢。

**Comment by Jianru-Lin** [comment]
@yangzj1992 目前没有见到过
