### ISSUE TITLE
我遇到个问题，不知道是不是个bug

### ISSUE THREAD

**Issue by guomh** [Jianru-Lin/lambda-view#17]
源代码是：
var btns = (config.btn || []).length, btndom;
结果用lv打开后变成了
var btns = config.btn || ([]).length,
btndom ;

估计是个bug，望知晓

**Comment by Jianru-Lin** [comment]
@guomh 确实，这是个 BUG，漏了一层括号，应该是这样才对：

```
var btns = (config.btn || ([])).length, 
    btndom;
```

谢谢反馈，我会修复这个问题。

**Comment by Jianru-Lin** [comment]
@guomh 已修复，执行以下命令安装最新版：

首先卸载当前版本

```
npm uninstall -g lambda-view
```

然后安装新版本

```
npm install -g lambda-view
```

安装成功后，可以执行 ```lv -v``` 查看版本号，应当是 v4.24.0 或以上。
