### ISSUE TITLE
十分感谢作者

### ISSUE THREAD

**Issue by ringcrl** [Jianru-Lin/lambda-view#2]
我是个刚入行不久的前端，读起公司代码起来十分费劲，甚至还用过一些思维导图工具把代码一点一点拆解，效率低下还不够直观，用了这个只需要 lv xx.js 就可以对代码有个大局认识啦，十分赞！可是有个问题是，作者说可以通过iPad来阅读源码，具体怎么实现呢？

**Comment by ringcrl** [comment]
哈哈 我又回来了 还有个问题 就是我在全部折叠的情况下 通过浏览器自带的 cmd+f 进行搜索 看看方法在哪里被调用的时候 并不能搜索出来哦 需要在全部展开的情况下才能被搜索出来 这个时候 假如我想知道某个方法或者变量在哪里被调用了 用什么方法操作比较好呢

**Comment by ringcrl** [comment]
一直在使用 简直停不下来 对读大量的代码也不那么畏惧了 就是读源码过程中发现了问题 回到原来的代码处进行编辑 这时候需要重新执行一次lv xxx.js 才能看到新的效果 作者大大可以告诉我你平时使用它的时候有哪些习惯吗 我觉得我这么使用还不能够发挥他的全部实力

**Comment by Jianru-Lin** [comment]
关于 ipad 阅读，关键是你需要有自己的一个 web 服务器，然后把 lv xxx.js 生成的 html 文件（是单独的一个文件，无外部依赖）发到自己的 web 服务器上，然后就可以通过 ipad 的浏览器打开进行访问。之后我可能会把这个功能整合好，不一定要这么麻烦。

另外你提到必须展开才能搜索的问题，这个会在后期解决。目前会先解决变量和作用域分析的问题，这个优先级比较高。有了这个分析，就能实现“点击跳转到定义”的功能。另外是添加注释的功能，优先级也比较高。完成这两个功能后，会把其它外围功能完善。

你能喜欢这个工具我很开心。欢迎你继续关注项目的后续进展。谢谢。😄

**Comment by zhw2590582** [comment]
不如作者做个在线上传js的版本，在线阅读

**Comment by Jianru-Lin** [comment]
@zhw2590582 没问题，正好有这个计划。
