### ISSUE TITLE
默认跑在23400端口，当我们不使用时，我们有办法kill这个么？

### ISSUE THREAD

**Issue by SuuQi** [Jianru-Lin/lambda-view#25]
![image](https://cloud.githubusercontent.com/assets/14038676/23240838/9efd3c68-f9aa-11e6-9745-27dd685b03fa.png)

**Comment by Jianru-Lin** [comment]
可以在任何时候执行下述命令关闭 lambda-view web server：

```
lv-svr stop
```

当你下一次通过 lv 命令打开别的文件时，会再次自动启动 lv-svr。
