### ISSUE TITLE
lv js文件时, 解析超时

### ISSUE THREAD

**Issue by cocody** [Jianru-Lin/lambda-view#26]
操作系统: window 7
浏览器: chrome 56.0.2924.87 (64-bit)
代理: ss 开了关了没影响

![](http://p1.bpimg.com/567571/7692c73d5c132033.png)

```js
PS C:\wamp\www\passport\source_pc> lv https://raw.githubusercontent.com/sofish/validator.js/master/validator.js
[2017-02-24 10:04:20] INFO processing target: https://raw.githubusercontent.com/sofish/validator.js/master/validator.js
[2017-02-24 10:04:41] ERROR connect ETIMEDOUT 151.101.100.133:443
```

输入`lv https://code.jquery.com/jquery-3.1.1.js` 

输出`done, see http://127.0.0.1:23400/lv.html?package=https%3A//code.jquery.com/jquery-3.1.1.js`

但内容是`Request failed, reload page to retry.`

![](http://p1.bqimg.com/567571/e00881e3b48aaadb.png)

**Comment by Jianru-Lin** [comment]
@cocody 已修复此问题，请更新到 v5.6.1
