### ISSUE TITLE
看不了压缩过的js

### ISSUE THREAD

**Issue by wushanchao** [Jianru-Lin/lambda-view#30]
比如看不了jquery.min.js

**Comment by Jianru-Lin** [comment]
@wushanchao 可以看，压缩与否无所谓，只要它还是 JavaScript 就可以。但是你需要耐心等待一段时间，如果浏览器提示你页面无响应，请点击继续等待。我会在后续优化一下性能。

```
lv https://code.jquery.com/jquery-3.1.1.min.js
```

![screen shot 2017-03-15 at 15 23 39](https://cloud.githubusercontent.com/assets/1057486/23937681/ad6e397a-0993-11e7-80ea-a241cbdeefb6.png)
