### ISSUE TITLE
win10安装之后显示  “lv” 命令出错

### ISSUE THREAD

**Issue by ghost** [Jianru-Lin/lambda-view#36]
这是安装完了之后运行的效果:
![image](https://user-images.githubusercontent.com/11428132/34726833-185d9ea4-f590-11e7-9d2e-64388384ebb5.png)

**Comment by ghost** [comment]
安装这个 是不是还要配置环境变量？

**Comment by ghost** [comment]
@Jianru-Lin @moschan @magicdawn

**Comment by run-ze** [comment]
你全局安装的其他npm包能运行吗？

**Comment by Jianru-Lin** [comment]
@ghost 不需要。试试在 cmd.exe 环境（而不是 powershell）环境下安装 lambda-view 并执行 lv 命令看看。另外确保你的 node.js（及 npm）是最新版本的。
