### ISSUE TITLE
the function after return may be render wrong position

### ISSUE THREAD

**Issue by wangduanduan** [Jianru-Lin/lambda-view#39]
lv version 5.8.0
lv https://raw.githubusercontent.com/jmesnil/stomp-websocket/master/lib/stomp.js

本来这个Frame函数是在立即执行表达式上面的，位置被改变到return下面，导致看起来很奇怪

![jietu20180320-205500](https://user-images.githubusercontent.com/16631306/37655714-036ed86e-2c81-11e8-8580-0f9f3da2169e.jpg)

**Comment by Jianru-Lin** [comment]
哈哈，这不是 bug，是 feature。因为 lv 会把函数声明置底并排序显示。这样做可以把很多比较混乱的代码展示得更有序，并且这不会改变语义。但确实有一些代码这样做反而有些奇怪。
