### ISSUE TITLE
windows 环境打开文件名 file.js 报错

### ISSUE THREAD

**Issue by mlyknown** [Jianru-Lin/lambda-view#4]
E:\MyProject\vuejs\vue\src>lv index.js
[2016-10-03 10:23:40] INFO read file from "E:\MyProject\vuejs\vue\src\index.js"...
[2016-10-03 10:23:40] INFO parsing javascript source code and generating html content...
[2016-10-03 10:23:40] ERROR Line 1: Unexpected token

**Comment by laughmaker** [comment]
mac下也报同样的错

**Comment by Jianru-Lin** [comment]
文件内容是怎么样的是不是含有 import/export 语句？

**Comment by Jianru-Lin** [comment]
@mlyknown @laughmaker 方便的话把文件内容提供一下，我试试 😄

**Comment by mlyknown** [comment]
import Vue from './instance/vue'
import installGlobalAPI from './global-api'
import { inBrowser, devtools } from './util/index'
import config from './config'

installGlobalAPI(Vue)

Vue.version = '1.0.26'

export default Vue

// devtools global hook
/\* istanbul ignore next */
setTimeout(() => {
  if (config.devtools) {
    if (devtools) {
      devtools.emit('init', Vue)
    } else if (
      process.env.NODE_ENV !== 'production' &&
      inBrowser && /Chrome\/\d+/.test(window.navigator.userAgent)
    ) {
      console.log(
        'Download the Vue Devtools for a better development experience:\n' +
        'https://github.com/vuejs/vue-devtools'
      )
    }
  }
}, 0)

就是有import/export，vuejs的入口文件 ==

**Comment by knight42** [comment]
@Jianru-Lin 
是不是含有 import/export 语句的文件暂时还不支持? 我这里运行时报错 Unexpected token

感觉可以用 babel-register 来做一下 transpile

**Comment by Jianru-Lin** [comment]
@mlyknown 好的，谢谢。我会修复这个问题。

@knight42 是的，import 和 export 的支持还有点小问题。不过已经找到解决办法。

**Comment by Jianru-Lin** [comment]
@mlyknown @knight42 @laughmaker 已经修复此问题。目前支持 import 和 export 语法了。

![screen shot 2016-10-12 at 00 31 10](https://cloud.githubusercontent.com/assets/1057486/19279602/a7b761c6-9014-11e6-8d5b-915b486114e1.png)

欢迎继续反馈。

**Comment by mlyknown** [comment]
ok  thanks
