### ISSUE TITLE
Linux 平台上可用 xdg-open 来打开网页

### ISSUE THREAD

**Issue by knight42** [Jianru-Lin/lambda-view#5]
大概是 exec('xdg-open ' + JSON.stringify(filename)).unref()

**Comment by Jianru-Lin** [comment]
好的，我试验后补上，谢谢 😄

**Comment by magicdawn** [comment]
see #8

**Comment by Jianru-Lin** [comment]
@magicdawn 谢谢，已合并。

**Comment by Jianru-Lin** [comment]
@knight42 问题已解决，试试卸载当前的 lambda-view 安装新版（4.5.0）
