### ISSUE TITLE
能否支持阅读引入的模块的源码?

### ISSUE THREAD

**Issue by knight42** [Jianru-Lin/lambda-view#6]

**Comment by Jianru-Lin** [comment]
能补充一些说明吗？ 😄

**Comment by knight42** [comment]
比方说入口文件 `index.js` 里有

``` js
var app = require('./app')
var routes = require('./routes')
....
```

我在 `lv index.js` 后能查看 `app.js` 以及 `routes.js` 的源码吗?

**Comment by linonetwo** [comment]
似乎在遇到 import 的时候会报错啊：

```
import generateAppByPlatform from './src/Route';


generateAppByPlatform('android');
```

```
[2016-10-03 21:16:27] ERROR Line 1: Unexpected token
```

似乎没有使用 babel 进行转码？
其实对于大型项目都可以使用项目内的 node_module 还有 .babelrc 来进行转码的。

**Comment by Jianru-Lin** [comment]
@knight42 好的我会认真考虑这个问题。

**Comment by Jianru-Lin** [comment]
@linonetwo 我正在修复这个问题。

**Comment by wuchuguang** [comment]
第一次使用，就很想知道 多模块js可不可以像

```
比方说入口文件 index.js 里有

var app = require('./app')
var routes = require('./routes')
....
我在 lv index.js 后能查看 app.js 以及 routes.js 的源码吗?
```

**Comment by Jianru-Lin** [comment]
@wuchuguang 暂时还不支持，但有这个计划

**Comment by EthanLin-TWer** [comment]
个人倒是觉得，跟进源码这个需求，直接导入到 IDE 中打开就可以实现啦，通过命令行和造轮子似乎反而曲折。

**Comment by linonetwo** [comment]
@linesh-simplicity 我觉得 up 主的工作以后说不定会集成到 vscode 之类的编辑器里作为插件啊，并没有造轮子。

**Comment by Jianru-Lin** [comment]
@knight42 @linonetwo @linesh-simplicity 这个功能已经实现了。参见这里：https://zhuanlan.zhihu.com/p/25375845
