### ISSUE TITLE
感谢&反馈

### ISSUE THREAD

**Issue by EthanLin-TWer** [Jianru-Lin/lambda-view#7]
首先❤️一下这个工具，觉得很棒，前端代码的追踪确实是感觉不够舒畅的一块，有了这个工具感觉会改善呢，不过更具体的反馈试用完了再来说~
## 反馈
- API 化。lambda-view 的核心功能是分析并展示代码结构，这个核心可以作为 API 被其他库或被用于三方用途，比如我之前就想过，写博客的时候，一些大型代码的展示要怎么做，仅仅通过 markdown 的代码块不能展示代码的依赖关系和设计结构，我需要一个小型的 IDE 环境：能够跟进代码源码，展示部分数据/调用结构等。这个时候，lambda-view 可能能够部分满足这个需求。再比如用于 Intellij/Eclipse/console 相关 GUI 插件的开发等。只是个想法，不知道作者有没有这样的打算，或者有什么指正

后续用了有什么反馈再来留言吧，第一感是个很不错的工具。点赞。

**Comment by Jianru-Lin** [comment]
@linesh-simplicity 谢谢你的建议。这是一个很大的愿景，希望能发展到那么强大。不过目前精力还无法顾及，我会把更多的时间用在开发基础功能上。 😄
