### ISSUE TITLE
打开文件夹？

### ISSUE THREAD

**Issue by hailiang-wang** [Jianru-Lin/lambda-view#9]
hi,

刚刚我试用了一下，体验很棒，不过现在还不支持打开文件夹。

![image](https://cloud.githubusercontent.com/assets/3538629/19062456/eb23e468-8a2c-11e6-8492-739f4f30eb27.png)

**Comment by Jianru-Lin** [comment]
@Samurais 是的，如果你需要打开多个文件：

``` bash
lv /path1/a.js /path2/b.js ...
```

如果你需要打开某个文件夹下的所有文件：

``` bash
lv /path/*.js
```
